# -*- coding: utf-8 -*-
"""Lab Report 3 IAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1to5gxdoE7SqL9sOZ7Y2AY2YtlUaK2Uyh
"""

# scholarship_app.py
import json
from typing import List, Dict, Any, Tuple
import operator
import streamlit as st

# ---------------------------------------------------------
# 1) Rule Engine (Minimal, same structure as your example)
# ---------------------------------------------------------
OPS = {
    "==": operator.eq,
    "!=": operator.ne,
    ">": operator.gt,
    ">=": operator.ge,
    "<": operator.lt,
    "<=": operator.le,
    "in": lambda a, b: a in b,
    "not_in": lambda a, b: a not in b,
}

# ---------------------------------------------------------
# DEFAULT RULES (Use EXACTLY as required in Question 2)
# ---------------------------------------------------------
DEFAULT_RULES = [
    {
        "name": "Top merit candidate",
        "priority": 100,
        "conditions": [
            ["cgpa", ">=", 3.7],
            ["co_curricular_score", ">=", 80],
            ["family_income", "<=", 8000],
            ["disciplinary_actions", "==", 0]
        ],
        "action": {
            "decision": "AWARD_FULL",
            "reason": "Excellent academic & co-curricular performance, with acceptable need"
        }
    },
    {
        "name": "Good candidate - partial scholarship",
        "priority": 80,
        "conditions": [
            ["cgpa", ">=", 3.3],
            ["co_curricular_score", ">=", 60],
            ["family_income", "<=", 12000],
            ["disciplinary_actions", "<=", 1]
        ],
        "action": {
            "decision": "AWARD_PARTIAL",
            "reason": "Good academic & involvement record with moderate need"
        }
    },
    {
        "name": "Need-based review",
        "priority": 70,
        "conditions": [
            ["cgpa", ">=", 2.5],
            ["family_income", "<=", 4000]
        ],
        "action": {
            "decision": "REVIEW",
            "reason": "High need but borderline academic score"
        }
    },
    {
        "name": "Low CGPA – not eligible",
        "priority": 95,
        "conditions": [
            ["cgpa", "<", 2.5]
        ],
        "action": {
            "decision": "REJECT",
            "reason": "CGPA below minimum scholarship requirement"
        }
    },
    {
        "name": "Serious disciplinary record",
        "priority": 90,
        "conditions": [
            ["disciplinary_actions", ">=", 2]
        ],
        "action": {
            "decision": "REJECT",
            "reason": "Too many disciplinary records"
        }
    }
]

# ---------------------------------------------------------
# Rule Engine Functions
# ---------------------------------------------------------
def evaluate_condition(facts: Dict[str, Any], cond: List[Any]) -> bool:
    field, op, value = cond
    if field not in facts or op not in OPS:
        return False
    return OPS[op](facts[field], value)

def rule_matches(facts: Dict[str, Any], rule: Dict[str, Any]) -> bool:
    return all(evaluate_condition(facts, c) for c in rule["conditions"])

def run_rules(facts: Dict[str, Any], rules: List[Dict[str, Any]]):
    matched = [r for r in rules if rule_matches(facts, r)]

    # No match → default review
    if not matched:
        return {"decision": "REVIEW", "reason": "No rule matched"}, []

    # Highest priority wins
    matched_sorted = sorted(matched, key=lambda r: r["priority"], reverse=True)
    best = matched_sorted[0]["action"]
    return best, matched_sorted


# ---------------------------------------------------------
# 2) Streamlit UI
# ---------------------------------------------------------
st.set_page_config(page_title="Scholarship Rule-Based System", layout="wide")
st.title("Scholarship Eligibility Rule-Based System")
st.caption("Enter applicant details and evaluate scholarship eligibility.")

with st.sidebar:
    st.header("Applicant Input")
    cgpa = st.number_input("CGPA", 0.0, 4.0, step=0.01, value=3.5)
    income = st.number_input("Family Income (RM)", min_value=0, step=100, value=6000)
    co_curricular = st.number_input("Co-curricular Score (0–100)", 0, 100, step=1, value=70)
    service_hours = st.number_input("Community Service Hours", min_value=0, step=1, value=30)
    semester = st.number_input("Current Semester", min_value=1, max_value=10, step=1, value=4)
    disciplinary = st.number_input("Disciplinary Actions", min_value=0, step=1, value=0)

    st.divider()
    st.header("Rules (JSON Editor)")
    rules_json = st.text_area(
        "Edit rules here",
        value=json.dumps(DEFAULT_RULES, indent=2),
        height=350
    )
    run = st.button("Evaluate", type="primary")

facts = {
    "cgpa": float(cgpa),
    "family_income": float(income),
    "co_curricular_score": int(co_curricular),
    "community_service_hours": int(service_hours),
    "semester": int(semester),
    "disciplinary_actions": int(disciplinary),
}

st.subheader("Applicant Facts")
st.json(facts)

# Convert JSON editor text → rules
try:
    rules = json.loads(rules_json)
except:
    st.error("Invalid JSON. Using default rules.")
    rules = DEFAULT_RULES

st.divider()

if run:
    action, matched_rules = run_rules(facts, rules)

    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("Decision Result")
        decision = action["decision"]
        reason = action["reason"]

        if decision == "AWARD_FULL":
            st.success(f"FULL SCHOLARSHIP — {reason}")
        elif decision == "AWARD_PARTIAL":
            st.info(f"PARTIAL SCHOLARSHIP — {reason}")
        elif decision == "REJECT":
            st.error(f"REJECTED — {reason}")
        else:
            st.warning(f"REVIEW — {reason}")

    with col2:
        st.subheader("Matched Rules (sorted by priority)")
        if matched_rules:
            for r in matched_rules:
                st.write(f"**{r['name']}** (priority={r['priority']})")
                st.caption(f"Action: {r['action']}")
                with st.expander("Conditions"):
                    st.code(json.dumps(r["conditions"], indent=2))
        else:
            st.info("No rules matched.")
else:
    st.info("Enter details and click **Evaluate**.")